### ISSUE TITLE
Pets by popular demand

### ISSUE THREAD

**Issue by brianamarie** [githubschool/april-24#10]
Hopefully we won't hear too much of these two today... 
<img width="606" alt="screen shot 2017-04-25 at 8 47 38 am" src="https://cloud.githubusercontent.com/assets/9906718/25388641/019d3d6e-2994-11e7-8c61-dc3f377008d7.png">
<img width="602" alt="screen shot 2017-04-25 at 8 47 52 am" src="https://cloud.githubusercontent.com/assets/9906718/25388644/026f484a-2994-11e7-98da-eabf5990c3e3.png">
<img width="612" alt="screen shot 2017-04-25 at 8 48 23 am" src="https://cloud.githubusercontent.com/assets/9906718/25388646/0346c3b0-2994-11e7-9d87-68bbc1a9f618.png">

**Comment by ghost** [comment]
Cuuute! Look at those eyes :D

**Comment by sjmp2** [comment]
Top pets! 10/10
